### ISSUE TITLE
No longer works with the current version of woocommerce (5.1)

### ISSUE THREAD

**Issue by RabiiMhamdi** [hasinhayder/paddle-woocommerce-3#6]
used to be working fine before but now the checkout displays a 404 page not found error from paddle

**Comment by MehbubRashid** [comment]
Hi @mhpekster can you try this one? https://wordpress.org/plugins/wc-paddle-payment-gateway/
I have tested it just now with latest version of woocommerce and wordpress

**Comment by RabiiMhamdi** [comment]
it seems to be the same problem, did you test it in a local environment? do I have to authenticate the domain? I'm on a local environment, I tried connecting my account both manually and via the button
also now the authentication tab under developer tools in my paddle account displays this "Auth access token not found"

**Comment by MehbubRashid** [comment]
@mhpekster of course it will not work in localhost..You need to have your domain approved in paddle (make sure you put your domain without www while submitting a domain for approval)

**Comment by DoYouKnowWhoElse** [comment]
Works for me @mhpekster @MehbubRashid 
@MehbubRashid Your think is gone btw

**Comment by MehbubRashid** [comment]
@RinnDog you can find it here https://github.com/MehbubRashid/paddle-payment-gateway-wc
